name: diffuse


default-extensions:
  - ExtendedDefaultRules
  - NoImplicitPrelude
  - OverloadedStrings


dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring == 0.10.*
  - cmark == 0.6.*
  - flow == 1.*
  - protolude
  - shikensu
  - text == 1.*
  - time == 1.*
  - unordered-containers == 0.2.*


executables:
  # 🚜
  build:
    main: Main.hs
    source-dirs:
      - system/Build
